AWSTemplateFormatVersion: '2010-09-09'
Description: 'WordPress Linux Instance with cross-stack references'

Parameters:
  YourIP:
    Type: String
    Default: 0.0.0.0/0
    Description: Your IP Address for HTTP access

  MySQLAdminPassword:
    Type: String 
    Description: Password for WordPress MySQL user

  InstanceType:
    Type: String
    Default: t2.micro
    Description: Select EC2 instance type for WordPress Instance.

Resources:
  WordPressEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP traffic from YourIP
      VpcId: !ImportValue 'VPC1ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref YourIP

  WordPressLinuxInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !ImportValue 'VPC1PublicSubnet1ID'
          GroupSet:
            - !Ref WordPressEC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel mariadb105 mariadb105-server
          wget http://ja.wordpress.org/latest-ja.tar.gz -P /tmp/
          tar zxvf /tmp/latest-ja.tar.gz -C /tmp
          cp -r /tmp/wordpress/* /var/www/html/
          chown apache:apache -R /var/www/html
          systemctl enable httpd.service
          systemctl start httpd.service
          systemctl enable mariadb
          systemctl start mariadb
          mysql -uroot -e 'CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8'
          mysql -uroot -e "GRANT ALL ON wordpress.* TO 'admin'@'localhost' IDENTIFIED BY '${MySQLAdminPassword}'"
      Tags:
        - Key: Name
          Value: 'WordPress-linux'

  WordPressEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      InstanceId: !Ref WordPressLinuxInstance
      Tags:
        - Key: Name
          Value: 'WordPress-linux-eip'

Outputs:
  WordPressURL:
    Description: "The HTTP URL of WordPress"
    Value: !Sub "http://${WordPressEIP}"
